# Copyright (c) 2024, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: Ballerina Integrator Documentation
site_description: Documentation for Ballerina Integrator
site_author: WSO2
site_url: https://bi.docs.wso2.com/

# Repository information
repo_name: wso2/docs-ballerina-integrator
repo_url: https://github.com/wso2/docs-bi
edit_uri: https://github.com/wso2/docs-bi/edit/main/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: WSO2 Ballerina Integrator - Documentation

# Configuration
theme:
  name: material
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/bi-logo.svg
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - content.action.view
  #highlightjs: true
  feature:
    tabs: true
  language: 'en'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Strict Mode
strict: false # Set to true to break the build if there are warnings

# Navigation structure
nav:
  - Home: index.md
  - Get started:
      - Introduction: get-started/introduction.md
      - Quick start guide: get-started/quick-start-guide.md
      - Key concepts: get-started/key-concepts.md
  - Install and Setup:
      - Install Ballerina Integrator: install-and-setup/install-ballerina-integrator.md
      - Install Integration Control Plane: install-and-setup/install-integration-control-plane.md
  - Learn:
      - learn/concepts/index.md
      - Automation:
        - learn/automation/index.md
        - Automated File Processor : learn/automation/file-processor.md
      - AI Agent:
        - Learn About AI Agent: learn/ai-agent/index.md
        - AI Chat Agent Integration: learn/ai-agent-integration.md # Kept Old ULR for SEO
        - AI Agenet in Other Integration: learn/ai-agent/ai-agent.md
      - Integration as API:
        - learn/integration-as-api/index.md
        - HTTP : 
          - learn/integration-as-api/http/index.md
          - Message Routing :
            # TODO: Need a landing page 
            - Message routing: learn/message-routing.md
            - Content Based Routing : learn/integration-as-api/http/route/content-based.md
            - Header Based Routing: learn/integration-as-api/http/route/header-based.md
          - Message Transformation:
            # TODO: Need a landing page
            - Message transformation: learn/message-transformation.md # Kept Old ULR for SEO
            - XML to JSON : learn/integration-as-api/http/transform/xml-to-json.md
            - JSON to XML : learn/integration-as-api/http/transform/json-to-xml.md
          - Service Ochestration:
            # TODO: Need a landing page
            - Multiple Service Integration : learn/integration-as-api/http/service-orchestration/multiple-service-integration.md
            - Service orchestration: learn/service-orchestration.md # Kept Old ULR for SEO
            - Redis Cache: learn/integration-as-api/http/service-orchestration/currency-conversion.md
      - Event Integration:
        - learn/event-integration/index.md
      - File Integration: # Had to use Integrations instead of Integration to support old link
        - learn/file-integrations/index.md
        - Directory Service:
          - learn/file-integrations/directory-service/index.md
          - File integration: learn/file-integration.md # Kept Old ULR for SEO
#      - Natural functions: learn/natural-functions.md # Kept Old ULR for SEO
      - Connections: learn/connctions/index.md
      - Data mapping: learn/data-mapping.md # Kept Old ULR for SEO
      - Configurable:
        - Learn About Configurable: learn/configurable/index.md
      - Developer Guides:
        - AI-assisted integration: learn/integration-ai.md
      - Testing:
        - Writing Tests: learn/testing/index.md
      - Enterprise Integration Patterns:
        - learn/enterprise-integration-patterns/index.md
        - learn/enterprise-integration-patterns/message-route.md
        - learn/enterprise-integration-patterns/message-translator.md
  - Deploy:
      - Deploy to Devant: deploy/deploy-to-devant.md
      - Deploy on VM as executable JAR: deploy/deploy-on-vm-as-executable-jar.md
      - Deploy as Docker image: deploy/deploy-as-docker-image.md
      

# Markdown extensions configuration
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list

# Plugins configuration
plugins:
  - search
  - markdownextradata: {}
  - exclude:
      glob:
        - wip/*
  - redirects:
      redirect_maps:

# Extra configuration
extra_css:
  # You can select a different theme for syntax highlighting by simply
  # selecting a different css file below from the available list.
  - assets/lib/highlightjs/styles/vs.min.css
  # Make sure to activate only one palette at a time.
  # If all the palettes are commented out, the default material theme palette will take over
  - assets/css/blue-palette-alt1.css
  # - assets/css/blue-palette-alt2.css
  # - assets/css/blue-palette.css
  # - assets/css/green-palette.css
  # - assets/css/orange-palette.css
  - assets/css/mitheme.css
  - assets/css/custom.css
  - assets/lib/json-formatter/json-formatter.css
  - assets/css/config-catalog.css
  - assets/lib/fontawesome-free-6.3.0-web/css/all.min.css
#  - assets/css/redoc.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/lib/json-formatter/json-formatter.umd.js
  - assets/js/mitheme.js
  # - assets/lib/backtotop/js/util.js
  # - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  # site_version: Uncomment to specify a version
  base_path: https://wso2.github.io/docs-bi
  # base_path: http://localhost:8000
